/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroTipoRouteImport } from './routes/cadastro.$tipo'
import { Route as LoginTipoRouteImport } from './routes/login.$tipo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroTipoRoute = CadastroTipoRouteImport.update({
  id: '/cadastro/$tipo',
  path: '/cadastro/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginTipoRoute = LoginTipoRouteImport.update({
  id: '/login/$tipo',
  path: '/login/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro/$tipo': typeof CadastroTipoRoute
  '/login/$tipo': typeof LoginTipoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro/$tipo': typeof CadastroTipoRoute
  '/login/$tipo': typeof LoginTipoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro/$tipo': typeof CadastroTipoRoute
  '/login/$tipo': typeof LoginTipoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro/$tipo' | '/login/$tipo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro/$tipo' | '/login/$tipo'
  id: '__root__' | '/' | '/cadastro/$tipo' | '/login/$tipo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroTipoRoute: typeof CadastroTipoRoute
  LoginTipoRoute: typeof LoginTipoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/$tipo': {
      id: '/cadastro/$tipo'
      path: '/cadastro/$tipo'
      fullPath: '/cadastro/$tipo'
      preLoaderRoute: typeof CadastroTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$tipo': {
      id: '/login/$tipo'
      path: '/login/$tipo'
      fullPath: '/login/$tipo'
      preLoaderRoute: typeof LoginTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroTipoRoute: CadastroTipoRoute,
  LoginTipoRoute: LoginTipoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
